### ISSUE TITLE
Question: how to configure backup

### ISSUE THREAD

**Issue by beyondwatts** [BeryJu/gravity#1004]
The documentation talks about being able to create S3 snapsnots (https://gravity.beryju.io/docs/backup/)

> Gravity’s inbuilt backup regularly saves etcd snapshots to a user-configured S3 endpoint and bucket. These snapshots can then be used to restore a cluster from scratch.
> 
> Starting with 0.4.5, Gravity will also keep 1 snapshot locally without any additional configuration, in the /data/backup directory. This snapshot can be restored just like other snapshots

How should the S3 bucket be configured? What is the snapshot frequency?

Note: creating an export dump from the command line is working successfully:
`gravity cli export /data/dump.json`

**Comment by BeryJu** [comment]
I updated https://gravity.beryju.io/docs/backup/role_config/ to explain these

**Comment by beyondwatts** [comment]
Thank you. I had missed that this is configured from the rest endpoint and not the UI
