### ISSUE TITLE
Apparent bug in Overview query graph

### ISSUE THREAD

**Issue by gjsmo** [BeryJu/gravity#600]
It appears that sometimes there is an additional data point added in the graph which causes a line to be added back to the bottom left corner of the graph. See the `memory` and `etcd` lines below.

![image](https://github.com/BeryJu/gravity/assets/12057767/ec757c2b-dc37-46c0-accc-c77d33d4a1a9)

**Comment by BeryJu** [comment]
fixed by c7ab40b5fe345be00eda84c5aaf370b46ecf7b02
