### ISSUE TITLE
CNAME records acting unlike how I would expect

### ISSUE THREAD

**Issue by ryan77627** [BeryJu/gravity#611]
Hello! First of all, thanks for this project, it seems to be the closest solution yet to the problem I am trying to solve right now.

I have a question about CNAME records that very well could be my own fault, but I cannot figure out: how do I actually use them? I have a zone that Gravity is authoritative for, and have set up some A records that point to various hosts in my network. I would expect to be able to set CNAME records to reference various services, however the CNAMEs never resolve properly. `nslookup` returns no answer, same with dig. Only way I can get an answer from Gravity is by specifically requesting a CNAME using `dig CNAME addr.ess.here`, which isn't great since that means the name doesn't work at all in any of my applications.

Example:

Zone: sub.domain.com

(Type -> Name -> Value)
A -> host1 -> 192.168.1.1
CNAME -> gravity -> host1.sub.domain.com

nslookup for gravity.sub.domain.com should result in 192.168.1.1 (canonical name = host1.sub.domain.com)

If more detail is needed please let me know

**Comment by mastpsp** [comment]
@BeryJu Hello! Thx for your project. CNAME records are not working for me, A records are working fine. When do you plan to fix this bug?
