### ISSUE TITLE
DHCP Relay does not appear to work

### ISSUE THREAD

**Issue by bbushvt** [BeryJu/gravity#618]
It doesn't appear that Gravity works with DHCP relays.  
```
gravity_1  | {"level":"info","ts":1692744765.2445304,"logger":"role.dhcp","msg":"DHCP packet","app":"gravity.beryju.io","instance":"dns01","version":"0.6.10-6ae1a926","request":"aaa6048c-7187-4fbb-b9de-efcf40035c3d-0xa92485f2","deviceIdentifier":"00:50:56:ae:63:fb","opCode":"BootRequest","hopCount":1,"transactionID":"0xa92485f2","flagsToString":"Unicast","clientIPAddr":"0.0.0.0","yourIPAddr":"0.0.0.0","serverIPAddr":"0.0.0.0","gatewayIPAddr":"192.168.202.1","hostname":"","clientIdentifier":"01005056ae63fb","messageType":"DISCOVER","client":"192.168.200.1:68"}
gravity_1  | {"level":"info","ts":1692744765.2449088,"logger":"role.dhcp","msg":"no scope found","app":"gravity.beryju.io","instance":"dns01","version":"0.6.10-6ae1a926","request":"aaa6048c-7187-4fbb-b9de-efcf40035c3d-0xa92485f2"}
```

Here is my gravity configuration for this scope:
![image](https://github.com/BeryJu/gravity/assets/1264513/cb64a662-78f1-48e5-8183-3309b5d47b3f)

**Comment by cfarence** [comment]
I had a similar issue with pfsense's DHCP relay. Packet captures showed the DHCP request was relayed to Gravity and that Gravity responded with an IP address from the correct scope but it never arrived and it didn't get relayed back to the end device. I've been meaning to investigate it further but just haven't had the time to do it yet.

**Comment by bbushvt** [comment]
What did the gravity logs show?  Mine is showing that it can't find the scope, but I'm not sure what information its using to look up which scope to use.

**Comment by BeryJu** [comment]
https://github.com/BeryJu/gravity/blob/main/pkg/roles/dhcp/scopes.go#L96-L120 is the logic for finding the scope for a request. I tested with a DHCP relay quite early in development and that worked fine (that was with the standard dhcp relay on vyos, which I think is isc-dhcp-relay)

Feel free to post any kind of packet capture here or send it to me @ jens@beryju.org, that would make figuring this out a lot easier

**Comment by BeryJu** [comment]
@bbushvt @cfarence could you try with the `ghcr.io/beryju/gravity:latest` build? The commit above should fix the issue

**Comment by cfarence** [comment]
@BeryJu Spun up a test network and flipped a DHCP relay on pfsense and it looks like it's not finding the scope

```
gravity-gravity-1  | {"level":"info","ts":1698203565.396064,"logger":"role.dhcp","msg":"DHCP packet","instance":"gravity1","version":"0.6.14-2f2df4ef","request":"09765a67-61e0-40bc-895e-230887ebf9b1-0xa9b28e89","deviceIdentifier":"00:50:56:80:b4:4b","opCode":"BootRequest","hopCount":1,"transactionID":"0xa9b28e89","flagsToString":"Unicast","clientIPAddr":"0.0.0.0","yourIPAddr":"0.0.0.0","serverIPAddr":"0.0.0.0","gatewayIPAddr":"172.16.20.1","hostname":"WIN-GQ2G2Q68F2U","clientIdentifier":"0100505680b44b","messageType":"DISCOVER","client":"10.30.10.1:67"}
gravity-gravity-1  | {"level":"info","ts":1698203565.3961825,"logger":"role.dhcp","msg":"no scope found","instance":"gravity1","version":"0.6.14-2f2df4ef","request":"09765a67-61e0-40bc-895e-230887ebf9b1-0xa9b28e89"}
```

![image](https://github.com/BeryJu/gravity/assets/3825621/846ca98f-0c35-4a61-b5e0-64c296cfa610)

**Comment by BeryJu** [comment]
The current :latest build fixes this issue

**Comment by bbushvt** [comment]
Just did a little test and its working in my home lab, thanks!
