### ISSUE TITLE
DNS not always resolving

### ISSUE THREAD

**Issue by bbushvt** [BeryJu/gravity#838]
So I've run into an issue and I'm not sure if its something I've not configured correctly or if its a bug.
This particular time (I've had the same issue with other DNS names), when I try and go to www.reddit.com I get a "Hmm. We’re having trouble finding that site." in the browser and from the command line (ping) it says (ping: www.reddit.com: Name or service not known)

The log has entries like this
{"level":"info","ts":1702770267.1026013,"logger":"role.dns","msg":"DNS Query","instance":"dns01","version":"0.7.0-a864f302","runtime":6,"client":"192.168.53.200","response":"NOERROR","queryNames":["www.reddit.com."],"queryTypes":["AAAA"],"answerRecords":["reddit.map.fastly.net."],"answerTypes":["CNAME"]}

So its getting the request, knows that its a CNAME, but doesn't resolve it any further.  If I manually ping the CNAME record "reddit.map.fastly.net", I get a response and from the logs it finds the A records

{"level":"info","ts":1702770297.6442485,"logger":"role.dns","msg":"DNS Query","instance":"dns01","version":"0.7.0-a864f302","runtime":10,"client":"192.168.53.200","response":"NOERROR","queryNames":["reddit.map.fastly.net."],"queryTypes":["A"],"answerRecords":["151.101.1.140","151.101.65.140","151.101.129.140","151.101.193.140"],"answerTypes":["A","A","A","A"]}

After that, if I try and ping www.reddit.com, it resolves correctly and I see this in the logs:
{"level":"info","ts":1702770299.9097157,"logger":"role.dns","msg":"DNS Query","instance":"dns01","version":"0.7.0-a864f302","runtime":4,"client":"192.168.53.200","response":"NOERROR","queryNames":["www.reddit.com."],"queryTypes":["A"],"answerRecords":["reddit.map.fastly.net.","151.101.1.140","151.101.65.140","151.101.129.140","151.101.193.140"],"answerTypes":["CNAME","A","A","A","A"]}

Any idea if this is a bug or do I have some misconfiguration?

**Comment by bbushvt** [comment]
The Root Zone has this configuration:
![image](https://github.com/BeryJu/gravity/assets/1264513/de9840ea-8b83-4611-8080-30e725a434bf)

**Comment by BeryJu** [comment]
There seems to be a bug in regards to CNAME stuff (especially after the recent CNAME fixes) in the memory and etcd handler, so for the time being disabling those works around this issue

**Comment by bbushvt** [comment]
How do you go about disabling them?

**Comment by tigattack** [comment]
@bbushvt Remove them from the handler configs in your zone settings.
