### ISSUE TITLE
Add support for OIDC variables as environment variables

### ISSUE THREAD

**Issue by CygnusHyoga** [BeryJu/gravity#931]
It would be nice to have support to define OIDC configuration by environment variables. To be able to configure the service automatically at the time of deployment, in a simple way and without extra manual steps. Thanks.

Variables:

- clientID
- clientSecret
- issuer
- redirectURL
- scopes

**Comment by BeryJu** [comment]
For the time being you can set a bootstrap token to do this via the API, I don't really want to add a special case just for these settings so the question would be more so about adding an option to provide any default config via environment variables

**Comment by CygnusHyoga** [comment]
Yes, I agree...adding an option to provide any default config via environment variables. 

It could also be interesting to add to gravity's terraform provider, a module to configure OIDC.

**Comment by BeryJu** [comment]
Oh yeah I thought this was already possible, but alas it is not yet

**Comment by BeryJu** [comment]
https://github.com/BeryJu/gravity/commit/1c9d9dbfe241601b84d1dbd00430be4025178893 describes how this can be done with the `IMPORT_CONFIGS` environment variable; leaving this open for terraform support
